import os
import sys
from datetime import datetime


def fix_pdb_file(input_path, output_path):
    """修复PDB文件格式，添加文件头、元素符号和结束标识"""
    # 准备标准文件头
    now = datetime.now()
    header = [
        "HEADER    GENERATED BY RFDIFFUSION              {:%d-%b-%y}".format(now),
        "MODEL        1"
    ]

    with open(input_path, 'r') as fin, open(output_path, 'w') as fout:
        # 写入文件头
        for line in header:
            fout.write(line.ljust(80) + '\n')

        # 处理原子记录
        for line in fin:
            line = line.strip()
            if not line:
                continue

            parts = line.split()

            # 只处理ATOM记录
            if parts[0] != "ATOM":
                continue

            # 解析原子记录
            atom_serial = parts[1]
            atom_name = parts[2]
            residue_name = parts[3]
            chain_id = parts[4]
            residue_seq = parts[5]
            x = parts[6]
            y = parts[7]
            z = parts[8]
            occupancy = parts[9] if len(parts) > 9 else "1.00"
            temp_factor = parts[10] if len(parts) > 10 else "0.00"

            # 确定元素符号
            if atom_name[0].isdigit():
                element = atom_name[1] if len(atom_name) > 1 else atom_name[0]
            else:
                element = atom_name[0]

            # 构造标准PDB记录 (80字符)
            pdb_line = (
                f"ATOM  {atom_serial:>5}  {atom_name:<4}{residue_name:>3} {chain_id}{residue_seq:>4}    "
                f"{x:>8}{y:>8}{z:>8}{occupancy:>6}{temp_factor:>6}          "
                f"{element:>2}"
            )

            # 确保行长度为80字符
            pdb_line = pdb_line.ljust(80)
            fout.write(pdb_line + '\n')

        # 添加结束标识
        fout.write("ENDMDL".ljust(80) + '\n')
        fout.write("END".ljust(80) + '\n')


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python fix_pdb.py <input_file> <output_file>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.exists(input_file):
        print(f"Error: Input file not found - {input_file}")
        sys.exit(1)

    print(f"Processing PDB file: {input_file}")
    fix_pdb_file(input_file, output_file)
    print(f"Fixed PDB file saved to: {output_file}")